### ISSUE TITLE
HTML Comment tags

### ISSUE THREAD

**Issue by Fella1990** [CroxxN/lapce-html#1]
The Language Server formatting appears to stop processing content after an HTML Comment Tag is used, even if that tag is closed.

![Screenshot 2023-01-06 185353](https://user-images.githubusercontent.com/31502347/210939269-78ed6c6e-9bbc-4318-83a4-7bfe5dd1369e.png)

**Comment by CroxxN** [comment]
This is not a LSP issue, rather a problem with lapce itself. Interestingly, if you use "<!-- --!>", lapce continues syntax highlighting but doesn't evoke the extension.

![Screenshot from 2023-01-08 21-50-36](https://user-images.githubusercontent.com/88525413/211207347-75be35e3-14e9-46aa-832c-85e419e97d18.png)

I suggest you open this issue in the lapce repo itself.
