### ISSUE TITLE
Updated extension

### ISSUE THREAD

**Issue by gldtn** [CroxxN/lapce-html#2]
Looking at your extension under Lapce it tells me to install languageserver-bin

Please update to: vscode-langservers-extracted should be installed globally. Install it with npm i -g vscode-langservers-extracted

Also how do I find the path to it? I tried:

whereis vscode-langservers-extracted

but no luck

**Comment by CroxxN** [comment]
Hi there. For the LSP to work, you must install the `vscode-html-languageserver-bin` package as indicated in the `README.md`. Regarding the path, you can invoke the LSP with:

`> html-languageserver --stdio`

To find the path:
`> whereis html-languageserver`

The LSP invokes `html-languageserver` specifically, so if you use difference LSP servers, the plugin may not work.

**Comment by gldtn** [comment]
Thanks, I was able to get it working!
