### ISSUE TITLE
Post-installation

### ISSUE THREAD

**Issue by bobbykjack** [CroxxN/lapce-html#3]
Once I've installed the plugin, how do I use it? I've run the vscode languageserver npm install, but I don't notice any difference in behaviour in Lapce. Do I need to explicitly run a "format" command? Shouldn't I get auto-formatting of HTML on-save now, since I've enabled 'format on save' in the settings?

**Comment by CroxxN** [comment]
This LSP currently doesn't provide a formatter. However, once you format with an external tool, Lapce will generally try to preserve the formatting. Also, if you have installed the directed npm package and installed the plugin, it should work out the box and provide suggestions (tags, attributions, auto-tag-close suggestions and more) right away.

Feel free to reopen this issue if this doesn't answer your queries.
